---
name: github-workflow
description: Test github workflow.
enabled: true

trigger:
  type: core.st2.webhook
  parameters:
    url: "st2_github_webhook"

criteria:
  trigger.body.user:
    type: equals
    pattern: "bitovi"

action:
  ref: st2_github_training.github_workflow
  parameters:
    user: "{{ trigger.body.user }}"
    path: "{{ trigger.body.path }}"
    repo: "{{ trigger.body.repo }}"